#!/usr/bin/env bash

# Download, build and install Ersap Java and C++ into "$ERSAP_HOME".
# If "$ERSAP_HOME" is not defined, then "<demo_root>/ersap" will be used.
#
# Ersap dependencies need to be installed in the system.
#
# Requirements:
#
#   CMake
#   Protocol Buffers
#   ZeroMQ
#
# Usage:
#
#   $ export ERSAP_HOME=~/dev/ersap-home  # optional
#   $ ./scripts/install-ersap

demo_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
deps_dir=${DEPS_DIR:-$demo_dir/deps}
build_dir=$deps_dir/ersap

# check ERSAP_HOME
if [ -z "$ERSAP_HOME" ]; then
    echo "ERSAP_HOME is not set."
    export ERSAP_HOME="$demo_dir/ersap"
    echo "Using ERSAP_HOME=\"$ERSAP_HOME\""
fi

# check CMake
if ! command -v cmake > /dev/null 2>&1; then
    cat << EOF >&2
Please install the CMake build tool.
EOF
    exit 1;
fi

{ mkdir -p "$build_dir" && cd "$build_dir"; } ||
    { echo "Could not create \"$build_dir\""; exit 1; }

echo "Installing Ersap..."
cmake_cmd=(cmake)
cmake_cmd+=("-DINSTALL_ERSAP=ON")
cmake_cmd+=("$demo_dir/.ci")

rm -f CMakeCache.txt
rm -f src/*-stamp/*-configure

"${cmake_cmd[@]}" && make
