#!/usr/bin/env bash

# Download, build and install OpenCV into "$OpenCV_ROOT" install prefix.
# If "$OpenCV_ROOT" is not defined, then "$ERSAP_HOME" will be used.
# If "$ERSAP_HOME" is not defined, then "<demo_root>/ersap" will be used.
#
# Requirements:
#
#   CMake
#   Apache Ant
#
# Usage:
#
#   $ export OpenCV_ROOT=/opt/opencv3  # optional
#   $ ./scripts/install-opencv

demo_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
deps_dir=${DEPS_DIR:-$demo_dir/deps}
build_dir=$deps_dir/opencv

# check ERSAP_HOME
# shellcheck disable=2154
if [ -z "$OpenCV_ROOT" ] && [ -z "$ERSAP_HOME" ]; then
    echo "ERSAP_HOME is not set."
    export ERSAP_HOME="$demo_dir/ersap"
    echo "Using ERSAP_HOME=\"$ERSAP_HOME\""
fi

# check CMake
if ! command -v cmake > /dev/null 2>&1; then
    cat << EOF >&2
Please install the CMake build tool.
EOF
    exit 1;
fi

# check Ant
if ! command -v ant > /dev/null 2>&1; then
    cat << EOF >&2
Please install Apache Ant build tool.
EOF
    exit 1;
fi

{ mkdir -p "$build_dir" && cd "$build_dir"; } ||
    { echo "Could not create \"$build_dir\""; exit 1; }

echo "Installing OpenCV to \"${OpenCV_ROOT:-$ERSAP_HOME}\"..."
cmake_cmd=(cmake)
cmake_cmd+=("-DINSTALL_OPENCV=ON")
if [ -n "$OpenCV_ROOT" ]; then
    cmake_cmd+=("-DOPENCV_INSTALL_DIR=$OpenCV_ROOT")
fi
cmake_cmd+=("$demo_dir/.ci")

rm -f CMakeCache.txt
rm -f src/*-stamp/*-configure

"${cmake_cmd[@]}" && make
